[2024-03-08 15:40:48,929: INFO: main: Welcome to our CNN Classifier app!]
[2024-03-11 16:22:31,764: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-11 16:22:31,769: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-11 16:22:31,770: INFO: common: created directory at: artifacts]
[2024-03-11 16:22:31,772: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-11 16:22:31,773: INFO: 986331348: Downloading data from https://drive.google.com/file/d/1zVDEEdASmLjU-Z3jIe0GtID_DhEINf0_/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-11 16:22:46,487: INFO: 986331348: Downloaded data from https://drive.google.com/file/d/1zVDEEdASmLjU-Z3jIe0GtID_DhEINf0_/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-11 22:20:08,154: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-11 22:20:08,156: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-11 22:20:08,157: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-11 22:20:08,157: INFO: common: created directory at: artifacts]
[2024-03-11 22:20:08,158: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-11 22:20:08,158: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1zVDEEdASmLjU-Z3jIe0GtID_DhEINf0_/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-11 22:20:31,760: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1zVDEEdASmLjU-Z3jIe0GtID_DhEINf0_/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-11 22:20:32,129: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-12 08:16:05,609: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-12 08:16:05,630: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-12 08:16:05,631: INFO: common: created directory at: artifacts]
[2024-03-12 08:18:41,006: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-12 08:18:41,010: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-12 08:18:41,012: INFO: common: created directory at: artifacts]
[2024-03-12 08:19:37,866: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-12 08:19:37,871: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-12 08:19:37,872: INFO: common: created directory at: artifacts]
[2024-03-12 08:29:09,811: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-12 08:29:09,815: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-12 08:29:09,817: INFO: common: created directory at: artifacts]
[2024-03-12 08:38:58,817: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-12 08:38:58,832: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-12 08:38:58,834: INFO: common: created directory at: artifacts]
[2024-03-12 08:38:58,835: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-12 08:39:14,072: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-12 09:01:33,865: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-12 09:01:33,868: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-12 09:01:33,870: INFO: common: created directory at: artifacts]
[2024-03-12 09:01:33,872: INFO: common: created directory at: artifacts\training]
[2024-03-12 15:02:57,963: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-12 15:02:57,976: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-12 15:02:57,978: INFO: common: created directory at: artifacts]
[2024-03-12 15:03:22,742: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-12 15:03:22,745: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-12 15:03:22,746: INFO: common: created directory at: artifacts]
[2024-03-12 15:03:32,905: INFO: common: json file saved at: scores.json]
[2024-03-12 15:03:36,115: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-03-12 15:03:36,599: INFO: builder_impl: Assets written to: C:\Users\dhanu\AppData\Local\Temp\tmp06yts3z8\model\data\model\assets]
[2024-03-12 15:49:23,897: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-12 15:49:23,909: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-12 15:49:23,911: INFO: common: created directory at: artifacts]
[2024-03-12 15:49:37,424: INFO: common: json file saved at: scores.json]
[2024-03-12 15:49:41,427: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-03-12 15:49:41,997: INFO: builder_impl: Assets written to: C:\Users\dhanu\AppData\Local\Temp\tmp5d_zwkm7\model\data\model\assets]
[2024-03-13 08:36:56,143: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-13 08:36:56,153: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-13 08:36:56,162: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-13 08:36:56,163: INFO: common: created directory at: artifacts]
[2024-03-13 08:36:56,164: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-13 08:36:56,164: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1zVDEEdASmLjU-Z3jIe0GtID_DhEINf0_/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-13 08:37:12,672: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1zVDEEdASmLjU-Z3jIe0GtID_DhEINf0_/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-13 08:37:13,369: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-13 08:37:13,369: INFO: main: *******************]
[2024-03-13 08:37:13,369: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-13 08:37:13,370: ERROR: main: name 'PrepareBaseModelTrainingPipeline' is not defined]
Traceback (most recent call last):
  File "main.py", line 22, in <module>
    prepare_base_model = PrepareBaseModelTrainingPipeline()
NameError: name 'PrepareBaseModelTrainingPipeline' is not defined
[2024-03-13 08:39:23,720: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-13 08:39:23,725: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-13 08:39:23,727: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-13 08:39:23,728: INFO: common: created directory at: artifacts]
[2024-03-13 08:39:23,729: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-13 08:39:23,729: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1zVDEEdASmLjU-Z3jIe0GtID_DhEINf0_/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-13 08:39:40,514: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1zVDEEdASmLjU-Z3jIe0GtID_DhEINf0_/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-13 08:39:41,109: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-13 08:39:41,110: INFO: main: *******************]
[2024-03-13 08:39:41,110: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-13 08:39:41,113: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-13 08:39:41,115: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-13 08:39:41,116: INFO: common: created directory at: artifacts]
[2024-03-13 08:39:41,116: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-13 08:39:41,802: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-13 08:39:42,125: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-13 08:39:42,126: INFO: main: *******************]
[2024-03-13 08:39:42,126: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-13 08:39:42,131: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-13 08:39:42,133: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-13 08:39:42,134: INFO: common: created directory at: artifacts]
[2024-03-13 08:39:42,135: INFO: common: created directory at: artifacts\training]
[2024-03-13 08:40:47,789: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-13 08:40:47,789: INFO: main: *******************]
[2024-03-13 08:40:47,790: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-03-13 08:40:47,794: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-13 08:40:47,797: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-13 08:40:47,799: INFO: common: created directory at: artifacts]
[2024-03-13 08:41:00,029: INFO: common: json file saved at: scores.json]
[2024-03-13 08:41:00,030: INFO: common: json file saved at: scores.json]
[2024-03-13 08:41:00,031: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-03-26 18:08:40,185: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-26 18:08:40,187: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-26 18:08:40,190: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-26 18:08:40,191: INFO: common: created directory at: artifacts]
[2024-03-26 18:08:40,191: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-26 18:08:40,191: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1zVDEEdASmLjU-Z3jIe0GtID_DhEINf0_/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-26 18:08:52,634: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1zVDEEdASmLjU-Z3jIe0GtID_DhEINf0_/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-26 18:08:53,086: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-26 18:09:02,146: INFO: stage_02_prepare_base_model: *******************]
[2024-03-26 18:09:02,146: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-26 18:09:02,149: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-26 18:09:02,150: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-26 18:09:02,150: INFO: common: created directory at: artifacts]
[2024-03-26 18:09:02,150: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-26 18:09:02,521: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-26 18:09:02,664: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-26 18:35:11,145: INFO: stage_03_model_training: *******************]
[2024-03-26 18:35:11,145: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2024-03-26 18:35:11,147: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-26 18:35:11,148: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-26 18:35:11,149: INFO: common: created directory at: artifacts]
[2024-03-26 18:35:11,149: INFO: common: created directory at: artifacts\training]
[2024-03-26 18:36:08,628: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-26 18:36:14,876: INFO: stage_04_model_evaluation: *******************]
[2024-03-26 18:36:14,876: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2024-03-26 18:36:14,879: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-26 18:36:14,881: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-26 18:36:14,881: INFO: common: created directory at: artifacts]
[2024-03-26 18:36:26,048: INFO: common: json file saved at: scores.json]
[2024-03-26 18:36:26,048: INFO: common: json file saved at: scores.json]
[2024-03-26 18:36:26,048: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-03-28 19:11:55,076: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.98.0.22:8080]
[2024-03-28 19:11:55,077: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-28 19:12:20,533: INFO: _internal: 127.0.0.1 - - [28/Mar/2024 19:12:20] "GET / HTTP/1.1" 200 -]
[2024-03-28 19:13:35,493: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\dhanu\anaconda3\envs\kidne\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dhanu\anaconda3\envs\kidne\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dhanu\anaconda3\envs\kidne\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\dhanu\anaconda3\envs\kidne\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dhanu\anaconda3\envs\kidne\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\dhanu\anaconda3\envs\kidne\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "D:\Projects\Github\MLOps-Projects\Project_1\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\Users\dhanu\anaconda3\envs\kidne\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\dhanu\anaconda3\envs\kidne\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\dhanu\anaconda3\envs\kidne\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-03-28 19:13:35,500: INFO: _internal: 127.0.0.1 - - [28/Mar/2024 19:13:35] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-03-28 19:14:06,324: INFO: _internal: 127.0.0.1 - - [28/Mar/2024 19:14:06] "GET / HTTP/1.1" 200 -]
[2024-03-28 19:14:12,573: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\dhanu\anaconda3\envs\kidne\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dhanu\anaconda3\envs\kidne\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dhanu\anaconda3\envs\kidne\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\dhanu\anaconda3\envs\kidne\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dhanu\anaconda3\envs\kidne\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\dhanu\anaconda3\envs\kidne\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "D:\Projects\Github\MLOps-Projects\Project_1\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\Users\dhanu\anaconda3\envs\kidne\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\dhanu\anaconda3\envs\kidne\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\dhanu\anaconda3\envs\kidne\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-03-28 19:14:12,575: INFO: _internal: 127.0.0.1 - - [28/Mar/2024 19:14:12] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
